<?php

namespace ContainerXc2CZi1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActionCrudControllerconfigureCrudService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OoSfY9L.App\Controller\Admin\ActionCrudController::configureCrud()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OoSfY9L.App\\Controller\\Admin\\ActionCrudController::configureCrud()'] = ($container->privates['.service_locator.OoSfY9L'] ?? $container->load('get_ServiceLocator_OoSfY9LService'))->withContext('App\\Controller\\Admin\\ActionCrudController::configureCrud()', $container);
    }
}
