<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLO2l3hu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLO2l3hu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLO2l3hu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLO2l3hu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLO2l3hu\App_KernelDevDebugContainer([
    'container.build_hash' => 'LO2l3hu',
    'container.build_id' => '976eff7d',
    'container.build_time' => 1750349828,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLO2l3hu');
