<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF74y3Un\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF74y3Un/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF74y3Un.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF74y3Un\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerF74y3Un\App_KernelDevDebugContainer([
    'container.build_hash' => 'F74y3Un',
    'container.build_id' => '3ab4008b',
    'container.build_time' => 1751641689,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF74y3Un');
