<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLBAxxCH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLBAxxCH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLBAxxCH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLBAxxCH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLBAxxCH\App_KernelDevDebugContainer([
    'container.build_hash' => 'LBAxxCH',
    'container.build_id' => '55e728ad',
    'container.build_time' => 1753296538,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLBAxxCH');
