<?php

namespace ContainerB6p6YXS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Pl5gSeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._Pl5gSe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._Pl5gSe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ContactController::contact' => ['privates', '.service_locator.i50h5v4.App\\Controller\\ContactController::contact()', 'getContactControllercontactService', true],
            'App\\Controller\\ContenuPageController::getContenusToutesPages' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ContenuPageController::getContenusToutesPages()', 'getContenuPageControllergetContenusToutesPagesService', true],
            'App\\Controller\\TarifPageController::getTarif' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\TarifPageController::getTarif()', 'getTarifPageControllergetTarifService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ContactController:contact' => ['privates', '.service_locator.i50h5v4.App\\Controller\\ContactController::contact()', 'getContactControllercontactService', true],
            'App\\Controller\\ContenuPageController:getContenusToutesPages' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ContenuPageController::getContenusToutesPages()', 'getContenuPageControllergetContenusToutesPagesService', true],
            'App\\Controller\\TarifPageController:getTarif' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\TarifPageController::getTarif()', 'getTarifPageControllergetTarifService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ContactController::contact' => '?',
            'App\\Controller\\ContenuPageController::getContenusToutesPages' => '?',
            'App\\Controller\\TarifPageController::getTarif' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ContactController:contact' => '?',
            'App\\Controller\\ContenuPageController:getContenusToutesPages' => '?',
            'App\\Controller\\TarifPageController:getTarif' => '?',
        ]);
    }
}
