<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Container extends \App\Entity\Container implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Designation_Container' => [parent::class, 'Designation_Container', null, 16],
        "\0".parent::class."\0".'Nom_Container' => [parent::class, 'Nom_Container', null, 16],
        "\0".parent::class."\0".'associerContenus' => [parent::class, 'associerContenus', null, 16],
        "\0".parent::class."\0".'associerTarifs' => [parent::class, 'associerTarifs', null, 16],
        "\0".parent::class."\0".'contenirs' => [parent::class, 'contenirs', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        'Designation_Container' => [parent::class, 'Designation_Container', null, 16],
        'Nom_Container' => [parent::class, 'Nom_Container', null, 16],
        'associerContenus' => [parent::class, 'associerContenus', null, 16],
        'associerTarifs' => [parent::class, 'associerTarifs', null, 16],
        'contenirs' => [parent::class, 'contenirs', null, 16],
        'id' => [parent::class, 'id', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
